### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by ghanavat** [damieng/jekyll-blog-comments#7]
Hi,

Thanks for sharing this here.

I have been battling with the configuration as instructed. But can't get it to work on my Jekyll blog.

For some strange reasons, it won't make any difference if 'commenting' is 'closed' or 'open'. The response form is always showing for my posts. (When it is on development environment)

And it doesn't work at all when the blog is published online. I see nothing in posts pages.

I have carefully read the instructions and missed nothing (I hope!). Please can you give me some advice?

**Comment by damieng** [comment]
Without seeing more of your configuration etc. it's hard to know what's going wrong.

You can checked out Phil Haack's blog which uses this, specifically you'll need to make sure you have the configuration setup correctly like this:  https://github.com/Haacked/haacked.com/blob/master/_config.yml#L39-L46  (make sure you include the emptyarray bit)

Your comments should be structured like this: https://github.com/Haacked/haacked.com/tree/master/_data/comments

You can also see how the includes are used in https://github.com/Haacked/haacked.com/tree/9eb393a14c5e1be192e876a5850b1797d17ac4b0/_includes but that pretty much matches the samples here.

**Comment by ghanavat** [comment]
Hey @damieng,
Thanks for your response. I have managed to get the comment form showing on my post page.

There is another problem which is stopping me to leave comments and it's the 'receiver' key in _config.yml file. What should I really put there? What do you mean by {your-receiver-site}?

I set is as this: receiver: https://codingmarvels.com/api/PostComment
But I get 404 when I press 'Confirm comment' button.

Below is my whole configuration file:

`# Welcome to Jekyll!`
`#`
`# This config file is meant for settings that affect your whole blog, values`
`# which you are expected to set up once and rarely edit after that. If you find`
`# yourself editing this file very often, consider using Jekyll's data files`
`# feature for the data you need to update frequently.`
`#`
`# For technical reasons, this file is *NOT* reloaded automatically when you use`
`# 'bundle exec jekyll serve'. If you change this file, please restart the server process.`

`# Site settings`
`# These are used to personalize your new site. If you look in the HTML files,`
`# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.`
`# You can create any custom variable you would like, and they will be accessible`
`# in the templates via {{ site.myvariable }}.`
`title: Coding Marvels`
`email: codingmarvels@ghanavat.co.uk`
`description: >- # this means to ignore newlines until "baseurl:"`
  `Coding marvels is my personal blog and I will be focusing on WebAssembly and mostly Blazor! Have you heard of Blazor? No? Yes?` `Doesn’t matter if the answer is yes or no. We’re gonna have a lot of fun together and we will figure out exciting stuff as we go` `along, which will help this blog to evolve and give values to others.`
`baseurl: "" # the subpath of your site, e.g. /blog`
`url: "/" # the base hostname & protocol for your site, e.g. https://codingmarvels.com`
`#twitter_username: Maybe!`
`#github_username:  jekyll`

`# Build settings`
`markdown: kramdown`
`theme: minima`
`plugins:`
  `- jekyll-feed`

`repository: "codingmarvels_blog"`

`comments:`
`  enabled: true`
`  show_count: true`
`  receiver: https://codingmarvels.com/api/PostComment`

`emptyArray: []`

`defaults: `
`-`
   `scope:`
   `path: ''`
    `type: pages`
   `values:`
    `layout: page`
    `author: saeedG`
 `-`
  `scope:`
   `path: '_posts'`
   `type: posts`
  `values:`
   `layout: post`
   `author: saeedG`
  `authors:`
   `saeedg:`
     `name: Saeed Ghanavat`
     `email:`
     `url: https://codingmarvels.com`

`exclude:'
  '- vendor`

**Comment by damieng** [comment]
You need an address that can turn form posts into github pull requests.

I wrote one that you can deploy to Azure Functions - you can find the source at https://github.com/Azure-Functions/jekyll-blog-comments but you will need to set this up on your own Azure account and link it to your github repository using the installation instructions in the README there.

**Comment by ghanavat** [comment]
After a few hours yesterday, I have deployed your function onto Azure Functions App. Thanks for your help. I have obtained the address and managed to have a POST request. Got this error message as below:
'Form value missing for post_id' - Can you help please?

Also, is deploying the .Net tool you've wrote onto Azure Functions App the only option? Considering it's a paid service.

**Comment by damieng** [comment]
It's a paid service but you get a large allowance of executions (1M seconds) before you get billed.  I've never been charged for my Azure Function although there is a small charge for the storage behind it.  It currently costs me $0.03 a month.

It's possible Azure's AWS Lambda might be cheaper although you also need use API Gateway on top of that to get HHTP posts to it.  Google also has Cloud Functions available which might be a better option if you want totally free as they allow 2M executions a month and I can't see any mention of storage charges with that.  https://cloud.google.com/functions/pricing#simple_background_function

The error message seems to indicate that this line has been somehow removed from your page?  https://github.com/damieng/jekyll-blog-comments/blob/master/jekyll/_includes/comment-new.html#L5

**Comment by ghanavat** [comment]
That line of the code exists in 'comment-new.html' file. I have included only that file in the post.html.  Also, I am still testing this locally. I don't need to supply post_id as a part of the POST request, do I? If not, then I don't know why I'm getting that error, despite the fact that, that line of the code you have mentioned above, does exist. :(

**Comment by damieng** [comment]
That line should include post_id as part of the request.  It needs to be sent so the azure function knows what post the comment is for.

**Comment by ghanavat** [comment]
As I am still testing it locally, I have to pass the post_id along with the other parameters I guess. I am using Postman to do this. When I stick post_id into the POST request, I get this error in Azure Functions App log file:

Value cannot be null.
Parameter name: token

Can you help please?

**Comment by damieng** [comment]
Yes, it requires you setup three configuration values on Azure for your function.  They are documented in the README https://github.com/Azure-Functions/jekyll-blog-comments

**Comment by ghanavat** [comment]
Thanks again. It's weird, but I have added them for my function. But all three of them removed/disappeared from the setting page. I don't have access to my token right now. Will test it again today.

Will keep you posted. :)

**Comment by ghanavat** [comment]
Hi again, the above message is now gone. I have managed to get the token which I had stored somewhere and set it to the correct variable in Azure Functions App.

I have another question, hopefully the last one :). I am getting this:
This Jekyll comments receiever does not handle forms for '$/'. You should point to your own instance.

Any idea on how to get this resolved?

**Comment by damieng** [comment]
There is protection in place to ensure other people do not point their
forms at your receiver.

Are you getting this error when trying from POSTMAN?  If so it's probably
the lack of a HTTP_REFERER header that contains the domain name you setup
in the azure config.

POSTMAN should let you add that to better fake what the real form post
would look like.

**Comment by ghanavat** [comment]
I am getting this error in development and production environment. I was getting the same error in Postman too.

**Comment by damieng** [comment]
What site are you running from?

What value do you have for `CommentWebsiteUrl` in your Azure Function config?   

They need to match.

**Comment by damieng** [comment]
That check is run by looking at the form post value "comment-site"  (not HTTP_REFERER my mistake).

It should be correctly sent by the form template via line https://github.com/damieng/jekyll-blog-comments/blob/master/jekyll/_includes/comment-new.html#L6

**Comment by ghanavat** [comment]
This is the url: https://codingmarvels.com - tried with and without `https://`.

The `CommentWebsiteUrl` is set to the above, as well as site.url which is in _config.yml file

**Comment by ghanavat** [comment]
Both `CommentWebsiteUrl` and `url` in _config.yml are set to the same value. I am getting the post_id error again. This is happening in production. Seems like that comment-new.html can't read the post slug.

**Comment by damieng** [comment]
If you view source on your form you should see all the `<input type="hidden" ` elements with the values.  Do they look correct?  Or are some of them not being resolved by the Jekyll template engine?

**Comment by ghanavat** [comment]
They all look correct. I am playing around with post.html. Initially I had this line `{% include comment-new.html %}` outside of the `<article>` tag. And I was getting the post_id error.
Then I have moved it here:
`<div class="post-content e-content" itemprop="articleBody">`
`    {{ content }}	`
`    {% include comment-new.html %}`
`  </div>  `
Now I am getting `object reference not set ...` error in Azure Function.

**Comment by damieng** [comment]
Does it tell you what line?

**Comment by ghanavat** [comment]
No unfortunately. I can monitor the log in Azure. And it's telling me this:

`String cannot be empty`
`Parameter name: name`
I am a million percent sure that name is passed as it's a required field.

**Comment by ghanavat** [comment]
I have removed azure function and re-done it. Still exact same error. I have noticed something in azure function app. When I run the function in azure app, I get the attached error:
![image](https://user-images.githubusercontent.com/17701090/51444029-f5e69d80-1ce9-11e9-9915-0b6d7e05c22e.png)

**Comment by ghanavat** [comment]
And this is the information in function log:

![image](https://user-images.githubusercontent.com/17701090/51444055-51b12680-1cea-11e9-9746-862ec88d484a.png)

I hope you can advise.

**Comment by damieng** [comment]
I've gone through the code again - the only place  I can see that would generate this error is this line https://github.com/Azure-Functions/jekyll-blog-comments/blob/master/JekyllBlogCommentsAzure/PostCommentToPullRequestFunction.cs#L63 

This would only happen if you did not configure the necessary application settings for the function as per the README.md

**Comment by ghanavat** [comment]
This is what I configured in app settings:

![image](https://user-images.githubusercontent.com/17701090/51444914-22081b80-1cf6-11e9-8f58-b4fbfd264c1f.png)

**Comment by damieng** [comment]
Could you also try adding this one - it was missing from the README;

`CommentFallbackCommitEmail`   (what email address you want the commits to be from if the form does not supply them - normally your own email address)

**Comment by ghanavat** [comment]
Done it. I get `post_id` missing value message when I am testing live through my blog site. But I get 500 server error, `String cannot be empty Parameter name: name`, when I'm trying to test via Postman.

**Comment by ghanavat** [comment]
If you take a look at my blog site, and navigate to the **welcome** post, you'll see that reading comments is working fine. I have created a test comment (Taken from your README, somewhere).
In terms of the `post_id`, in the `comments-new.html` file, where `slug` is being read from? I don't see this to be defined in`_config.yml`.

**Comment by ghanavat** [comment]
This is my blog url: https://codingmarvels.com

**Comment by damieng** [comment]
The post_id field is blank on your form;

![image](https://user-images.githubusercontent.com/118951/51486602-fb79cd00-1d55-11e9-983a-6a755bf472d6.png)

Can you make sure you included comments.html rather than comments-new.html as the former sets up the slug etc;

https://github.com/damieng/jekyll-blog-comments/blob/master/jekyll/_includes/comments.html#L2

**Comment by ghanavat** [comment]
Thanks made changes as advised.

I don't have the `post_id` missing error anymore. 

But the 500 internal server error is back. And it's complaining about the `parameter name`. 

I have removed `comment-new` and now only using `comments.html`. Removed `commenting = open` from default in _config.yml. And added `commenting = open` in my welcome post.

**Comment by ghanavat** [comment]
Hey @damieng,
I was an idiot. In the README, you clearly said how to set the `PullRequestRepository`, which is `{name}/{repo}`. Instead, I somehow decided to blindly put the whole url of my repo in Azure app setting. I was reading the code, which you have sent me the link to, and realised you are using split function to separate name and repo in order to send the comment to my GitHub.

Having the whole url in appsetting obviously confused the split function as there would be multiple arrays out of it.

I have posted a few test comments and am able to see the pull requests.

Thanks a million for your help. I believe this issue here would help number of other people who would like to try this solution.

**Comment by damieng** [comment]
I'm also going to try and put some extra parameter and configuration setting code in shortly to help better diagnose setup issues.

Glad it is working for you!

**Comment by ghanavat** [comment]
Great! Let me know if you need someone to test it etc...

**Comment by ghanavat** [comment]
I have a strange problem. Comments won't show up in one of my posts. The pull request(s) has been merged and I can see the `.yml` file for it. But it won't show up on the post page. This particular comment has a title longer than the others (One word title).

Does the length of the post title would make any impact on how the comments are going to appear?

**Comment by damieng** [comment]
The lines here https://github.com/damieng/jekyll-blog-comments/blob/master/jekyll/_includes/comments.html#L1-L2 determine what name to use for both the folder in which to read the comments from and what to post back to the server as the post_id so it too can use/create the necessary folder.

It's possible some special characters will be HTML encoded and not correctly unencoded.

Go to the page on your site that isn't including the comments and look for the `<input type="hidden" name="post_id"...` and see what value it has.  This value should exactly match the folder name inside your `_data/comments` folder in your repo.

If it does not can you tell me what they both are?

**Comment by ghanavat** [comment]
There are differences between them:

The one on the page is: `brief_story_behind_my_blog`
And the one in `_data\comments` is: `brief-story-behind-my-blog`

**Comment by damieng** [comment]
Can you try the updated comments.html - it now replaces `_` with `-`.  It seems `_` is the default but my blog was using `-` so they were mismatched.

**Comment by ghanavat** [comment]
Yes that fixed the problem! Thanks.
